
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package josq.lenguajes.automatas;

/** CUP generated interface containing symbol constants. */
public interface ParserDashbSym {
  /* terminals */
  public static final int KD_CHART = 12;
  public static final int MI_TEXTO = 2;
  public static final int KD_HEADER = 31;
  public static final int KD_PONTS = 34;
  public static final int KD_FOOTER = 32;
  public static final int MI_URL = 3;
  public static final int KD_YLABEL = 26;
  public static final int KD_KEYWORDS = 33;
  public static final int KD_DESCRIP = 15;
  public static final int EOF = 0;
  public static final int KD_CATEGORY = 20;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int KD_DATA = 11;
  public static final int KD_BACKGR = 17;
  public static final int MI_INTEGER = 4;
  public static final int IZQCORCH = 8;
  public static final int KD_COLOR = 22;
  public static final int KD_LINK = 24;
  public static final int DERCORCH = 9;
  public static final int KD_SIZE = 30;
  public static final int KD_TITLE = 14;
  public static final int KD_FONTSIZE = 19;
  public static final int IZQLLAVE = 6;
  public static final int KD_LINE = 35;
  public static final int KD_LEGEND = 27;
  public static final int KD_XLABEL = 25;
  public static final int MI_COLOR = 5;
  public static final int KD_ICON = 23;
  public static final int DERLLAVE = 7;
  public static final int KD_NAME = 36;
  public static final int KD_FONTFAM = 18;
  public static final int KD_VALUE = 21;
  public static final int KD_Y = 29;
  public static final int KD_X = 28;
  public static final int KD_LABEL = 13;
  public static final int KD_COPYR = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MI_TEXTO",
  "MI_URL",
  "MI_INTEGER",
  "MI_COLOR",
  "IZQLLAVE",
  "DERLLAVE",
  "IZQCORCH",
  "DERCORCH",
  "COMA",
  "KD_DATA",
  "KD_CHART",
  "KD_LABEL",
  "KD_TITLE",
  "KD_DESCRIP",
  "KD_COPYR",
  "KD_BACKGR",
  "KD_FONTFAM",
  "KD_FONTSIZE",
  "KD_CATEGORY",
  "KD_VALUE",
  "KD_COLOR",
  "KD_ICON",
  "KD_LINK",
  "KD_XLABEL",
  "KD_YLABEL",
  "KD_LEGEND",
  "KD_X",
  "KD_Y",
  "KD_SIZE",
  "KD_HEADER",
  "KD_FOOTER",
  "KD_KEYWORDS",
  "KD_PONTS",
  "KD_LINE",
  "KD_NAME"
  };
}

