package josq.lenguajes.modelos;

public enum Index
{
    SD_PROPERTY, SD_GRAFICOS,
    ERROR,
    MI_TEXTO,MI_URL,MI_INTEGER,MI_COLOR,
    IZQLLAVE,DERLLAVE,IZQCORCH,DERCORCH,COMA,
    KD_TITLE,KD_DESCRIP,KD_KEYWORDS,KD_HEADER,KD_FOOTER,KD_BACKGR,KD_FONTFAM,KD_FONTSIZE,
    KD_DATA,KD_CHART,KD_LABEL,KD_COPYR,
    KD_CATEGORY,KD_VALUE,KD_COLOR,KD_ICON,KD_LINK,
    KD_XLABEL,KD_YLABEL,KD_LEGEND,KD_X,KD_Y,KD_SIZE,
    KD_PONTS,KD_LINE,KD_NAM,
    ;
}