
package josq.lenguajes.automatas;

// antes de la clase parser

import java.util.List;
import java.util.ArrayList;
//import java_cup.runtime.*;
import josq.lenguajes.modelos.*;

// NOTA: %cupsym en jflex
// parser=MyParser, sym=MyParserSym
class ParserDashb;

// dentro de la clase parser
// parser code {: :}

// metodo user_init() de la clase parser generada
// init with {: :}

// metodo scan() de la clase parser generada
// scan with {: :}

// dentro de la clase action
action code {:
    private void print(String texto){ System.out.print(texto); }

    private void expectedSym()
    {
        List<Integer> ids = expected_token_ids();
        StringBuilder idsName = new StringBuilder();
        for (int i : ids) idsName.append(symbl_name_from_id(i)+" ");
        print("@expected: "+idsName.toString()+"\n");
        print("_<\n");
    }

    StringBuilder log(String mensaje) {
        return Registros.sintactico.append(mensaje);
    }
:}

// #%#%#%#% SIMBOLOS #%#%#%#%
// terminal [Type2] mySymbol1, mySymbol2 ;
// non terminal [Type2] mySymbol1, mySymbol2 ;

// #%#%#%#% TERMINALES #%#%#%#%

terminal String MI_TEXTO, MI_URL, MI_INTEGER, MI_COLOR ;

terminal IZQLLAVE ;
terminal DERLLAVE ;
terminal IZQCORCH ;
terminal DERCORCH ;
terminal COMA ;

terminal KD_DATA ;
terminal KD_CHART ;
terminal KD_LABEL ;
terminal KD_TITLE ;
terminal KD_DESCRIP ;
terminal KD_COPYR ;
terminal KD_BACKGR ;
terminal KD_FONTFAM ;
terminal KD_FONTSIZE ;
terminal KD_CATEGORY ;
terminal KD_VALUE ;
terminal KD_COLOR ;
terminal KD_ICON ;
terminal KD_LINK ;
terminal KD_XLABEL ;
terminal KD_YLABEL ;
terminal KD_LEGEND ;
terminal KD_X ;
terminal KD_Y ;
terminal KD_SIZE ;
terminal KD_HEADER ;
terminal KD_FOOTER ;
terminal KD_KEYWORDS ;
terminal KD_PONTS ;
terminal KD_LINE ;
terminal KD_NAME ;

// #%#%#%#% NO TERMINALES #%#%#%#%

non terminal Dashb dashboard ;

non terminal ArrayList<Par> content, content2, content3 ;

non terminal Par property ;
non terminal ArrayList<Par> properties, propertyList ;

non terminal Object grafico ;
non terminal ArrayList<Object> graficos ;

non terminal Barras barras ;
non terminal Barras.Data barrasDataValue ;
non terminal ArrayList<Barras.Data> barrasData, barrasDataList, barrasDataList2 ;

non terminal BarrasXt barrasXt ;
non terminal BarrasXt.Data barrasXtDataValue ;
non terminal ArrayList<BarrasXt.Data> barrasXtData, barrasXtDataList, barrasXtDataList2 ;

non terminal Pastel pastel ;
non terminal Pastel.Data pastelDataValue ;
non terminal ArrayList<Pastel.Data> pastelData, pastelDataList, pastelDataList2 ;

non terminal PastelXt pastelXt ;
non terminal PastelXt.Data pastelXtDataValue ;
non terminal ArrayList<PastelXt.Data> pastelXtData, pastelXtDataList, pastelXtDataList2 ;

non terminal Chart2 pastelXtChart ;

non terminal Chart1 chart ;

non terminal Puntos puntos ;
non terminal Puntos.Data puntosDataValue ;
non terminal ArrayList<Puntos.Data> puntosData, puntosDataList, puntosDataList2 ;

non terminal PuntosXt puntosXt ;
non terminal PuntosXt.Data puntosXtDataValue ;
non terminal ArrayList<PuntosXt.Data> puntosXtData, puntosXtDataList, puntosXtDataList2 ;

non terminal Lineas lineas ;
non terminal Lineas.Data lineasDataValue ;
non terminal ArrayList<Lineas.Data> lineasData, lineasDataList, lineasDataList2  ;

non terminal LineasXt lineasXt ;
non terminal LineasXt.Data lineasXtDataValue ;
non terminal ArrayList<LineasXt.Data> lineasXtData, lineasXtDataList, lineasXtDataList2 ;

non terminal Tarjeta tarjeta, tarjetaData ;
non terminal TarjetaXt tarjetaXt, tarjetaXtData ;

non terminal ArrayList<String> keywords, keywordList, keywordList2 ;

non terminal Lineas.Data.Punto pointValue ;
non terminal ArrayList<Lineas.Data.Punto> points, pointList, pointList2 ;

non terminal LineasXt.Data.Punto pointXtValue ;
non terminal ArrayList<LineasXt.Data.Punto> pointsXt, pointXtList, pointXtList2 ;

non terminal String title, description, header, footer, backgr, fontFam, fontSize ;
non terminal String category, value ;
non terminal String xLabel, yLabel ;
non terminal String color ;
non terminal String legend ;
non terminal String xValue ;
non terminal String yValue ;
non terminal String name ;
non terminal String size ;
non terminal String label ;
non terminal String icon ;
non terminal String link ;
non terminal String copyright ;
non terminal String lineStyle ; 

// PRODUCCIONES

// definicion de la produccion inicial
start with dashboard ;

dashboard ::=
    IZQLLAVE content:w1 DERLLAVE {: RESULT= Dashb.newDashb(w1); :}
;
content ::= 
    properties:w1 {: ArrayList<Par> list= new ArrayList<>(); list.add(new Par(Index.SD_PROPERTY,w1)); RESULT=list; :}
    | properties:w1 content2:w2 {: w2.add(new Par(Index.SD_PROPERTY,w1)); RESULT=w2; :}
    | properties:w1 content2:w2 properties:w3 {: w2.add(new Par(Index.SD_PROPERTY,w1)); w2.add(new Par(Index.SD_PROPERTY,w3)); RESULT=w2; :}
    | graficos:w1 content3:w2 {: w2.add(new Par(Index.SD_GRAFICOS,w1)); RESULT=w2; :}
    | graficos:w1 content3:w2 graficos:w3 {: w2.add(new Par(Index.SD_GRAFICOS,w1)); w2.add(new Par(Index.SD_GRAFICOS,w3)); RESULT=w2; :}
;
content2 ::=
    graficos:w1 {: ArrayList<Par> list= new ArrayList<>(); list.add(new Par(Index.SD_GRAFICOS,w1)); RESULT=list; :}
    | content2:w1 properties:w2 graficos:w3 {: w1.add(new Par(Index.SD_PROPERTY,w2)); w1.add(new Par(Index.SD_GRAFICOS,w3)); RESULT=w1; :}
;
content3 ::=
    properties:w1 {: ArrayList<Par> list= new ArrayList<>(); list.add(new Par(Index.SD_PROPERTY,w1)); RESULT=list; :}
    | content3:w1 graficos:w2 properties:w3 {: w1.add(new Par(Index.SD_GRAFICOS,w2)); w1.add(new Par(Index.SD_PROPERTY,w3)); RESULT=w1; :}
;

// PROPERTIES >>>>>>>>>>>>>>>>>>>
properties ::= 
    property:w1 {: ArrayList<Par> list= new ArrayList<>(); if(w1!=null) list.add(w1); RESULT=list; :}
    | property:w1 COMA {: ArrayList<Par> list= new ArrayList<>(); if(w1!=null) list.add(w1); RESULT=list; :}
    | properties:w1 property:w2 {: if(w2!=null) w1.add(w2); RESULT=w1; :}
    | properties:w1 property:w2 COMA {: if(w2!=null) w1.add(w2); RESULT=w1; :}
;
property ::= 
    title:w1         {: RESULT= new Par(Index.KD_TITLE,w1); :}
    | description:w1 {: RESULT= new Par(Index.KD_DESCRIP,w1); :}
    | keywords:w1    {: RESULT= new Par(Index.KD_KEYWORDS,w1); :}
    | header:w1      {: RESULT= new Par(Index.KD_HEADER,w1); :}
    | footer:w1      {: RESULT= new Par(Index.KD_FOOTER,w1); :}
    | backgr:w1      {: RESULT= new Par(Index.KD_BACKGR,w1); :}
    | fontFam:w1     {: RESULT= new Par(Index.KD_FONTFAM,w1); :}
    | fontSize:w1    {: RESULT= new Par(Index.KD_FONTSIZE,w1); :}
    | error:w1 MI_TEXTO:w2 {: RESULT=null; log("\n@parser[ property ] "+w1left+"-"+w2right+"\n\n"); :}
    | error:w1 MI_COLOR:w2 {: RESULT=null; log("\n@parser[ property ] "+w1left+"-"+w2right+"\n\n"); :}
    | error:w1 DERCORCH:w2 {: RESULT=null; log("\n@parser[ property ] "+w1left+"-"+w2right+"\n\n"); :}
    | error:w1 DERLLAVE:w2 {: RESULT=null; log("\n@parser[ property ] "+w1left+"-"+w2right+"\n\n"); :}
;

// GRAFICOS >>>>>>>>>>>>>>>>>>>
graficos ::=
    grafico:w1 {: ArrayList<Object> list = new ArrayList<>(); if(w1!=null) list.add(w1); RESULT=list; :}
    | graficos:w1 grafico:w2 {: if(w2!=null) w1.add(w2); RESULT=w1; :}
;
grafico ::=
    barras:w1      {: RESULT=w1; :}
    | barrasXt:w1  {: RESULT=w1; :}
    | pastel:w1    {: RESULT=w1; :}
    | pastelXt:w1  {: RESULT=w1; :}
    | puntos:w1    {: RESULT=w1; :}
    | puntosXt:w1  {: RESULT=w1; :}
    | lineas:w1    {: RESULT=w1; :}
    | lineasXt:w1  {: RESULT=w1; :}
    | tarjeta:w1   {: RESULT=w1; :}
    | tarjetaXt:w1 {: RESULT=w1; :}
    | IZQLLAVE:w1 error:w2 DERLLAVE:w3 {: RESULT=null; log("\n@parser[ grafico ] "+w1left+"-"+w3right+"\n\n"); :}
;

// BARRAS >>>>>>>>>>>>>>>>>>>
// barras
barras ::=
    IZQLLAVE barrasData:w1 DERLLAVE {: RESULT= new Barras(w1); :}
;
barrasData ::= KD_DATA IZQCORCH barrasDataList:w1 DERCORCH {: RESULT=w1; :}
;
barrasDataList ::= 
    barrasDataValue:w1 {: ArrayList<Barras.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | barrasDataList2:w1 barrasDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
barrasDataList2 ::=
    barrasDataValue:w1 COMA {: ArrayList<Barras.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | barrasDataList2:w1 barrasDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
barrasDataValue ::=
    IZQLLAVE category:w1 COMA value:w2 DERLLAVE {: RESULT= new Barras.Data(w1,w2); :}
    | IZQLLAVE value:w2 COMA category:w1 DERLLAVE {: RESULT= new Barras.Data(w1,w2); :}
;

// barrasXt
barrasXt ::= 
    IZQLLAVE barrasXtData:w1 COMA chart:w2 DERLLAVE {: RESULT= new BarrasXt(w1,w2); :}
    | IZQLLAVE chart:w2 COMA barrasXtData:w1 DERLLAVE {: RESULT= new BarrasXt(w1,w2); :}
;
barrasXtData ::= KD_DATA IZQCORCH barrasXtDataList:w1 DERCORCH {: RESULT=w1; :}
;
barrasXtDataList ::= 
    barrasXtDataValue:w1 {: ArrayList<BarrasXt.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | barrasXtDataList2:w1 barrasXtDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
barrasXtDataList2 ::=
    barrasXtDataValue:w1 COMA {: ArrayList<BarrasXt.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | barrasXtDataList2:w1 barrasXtDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
barrasXtDataValue ::=
    IZQLLAVE category:w1 COMA value:w2 COMA color:w3 DERLLAVE {: RESULT= new BarrasXt.Data(w1,w2,w3); :}
    | IZQLLAVE category:w1 COMA color:w3 COMA value:w2 DERLLAVE {: RESULT= new BarrasXt.Data(w1,w2,w3); :}
    | IZQLLAVE value:w2 COMA category:w1 COMA color:w3 DERLLAVE {: RESULT= new BarrasXt.Data(w1,w2,w3); :}
    | IZQLLAVE value:w2 COMA color:w3 COMA category:w1 DERLLAVE {: RESULT= new BarrasXt.Data(w1,w2,w3); :}
    | IZQLLAVE color:w3 COMA value:w2 COMA category:w1 DERLLAVE {: RESULT= new BarrasXt.Data(w1,w2,w3); :}
    | IZQLLAVE color:w3 COMA category:w1 COMA value:w2 DERLLAVE {: RESULT= new BarrasXt.Data(w1,w2,w3); :}
;

// PASTEL >>>>>>>>>>>>>>>>>>>
// pastel
pastel ::= IZQLLAVE pastelData:w1 DERLLAVE {: RESULT= new Pastel(w1); :}
;
pastelData ::= KD_DATA IZQCORCH pastelDataList:w1 DERCORCH {: RESULT=w1; :}
;
pastelDataList ::= 
    pastelDataValue:w1 {: ArrayList<Pastel.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pastelDataList2:w1 pastelDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
pastelDataList2 ::=
    pastelDataValue:w1 COMA {: ArrayList<Pastel.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pastelDataList2:w1 pastelDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
pastelDataValue ::= 
    IZQLLAVE label:w1 COMA value:w2 DERLLAVE {: RESULT= new Pastel.Data(w1,w2); :}
    | IZQLLAVE value:w2 COMA label:w1 DERLLAVE {: RESULT= new Pastel.Data(w1,w2); :}
;

// pastelXt
pastelXt ::= 
    IZQLLAVE pastelXtData:w1 COMA pastelXtChart:w2 DERLLAVE {: RESULT= new PastelXt(w1,w2); :}
    | IZQLLAVE pastelXtChart:w2 COMA pastelXtData:w1 DERLLAVE {: RESULT= new PastelXt(w1,w2); :}
;
pastelXtData ::= KD_DATA IZQCORCH pastelXtDataList:w1 DERCORCH {: RESULT=w1; :}
;
pastelXtDataList ::= 
    pastelXtDataValue:w1 {: ArrayList<PastelXt.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pastelXtDataList2:w1 pastelXtDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
pastelXtDataList2 ::=
    pastelXtDataValue:w1 COMA {: ArrayList<PastelXt.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pastelXtDataList2:w1 pastelXtDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
pastelXtDataValue ::= 
    IZQLLAVE label:w1 COMA value:w2 COMA color:w3 DERLLAVE {: RESULT= new PastelXt.Data(w1,w2,w3); :}
    | IZQLLAVE label:w1 COMA color:w3 COMA value:w2 DERLLAVE {: RESULT= new PastelXt.Data(w1,w2,w3); :}
    | IZQLLAVE value:w2 COMA label:w1 COMA color:w3 DERLLAVE {: RESULT= new PastelXt.Data(w1,w2,w3); :}
    | IZQLLAVE value:w2 COMA color:w3 COMA label:w1 DERLLAVE {: RESULT= new PastelXt.Data(w1,w2,w3); :}
    | IZQLLAVE color:w3 COMA value:w2 COMA label:w1 DERLLAVE {: RESULT= new PastelXt.Data(w1,w2,w3); :}
    | IZQLLAVE color:w3 COMA label:w1 COMA value:w2 DERLLAVE {: RESULT= new PastelXt.Data(w1,w2,w3); :}
;

// PUNTOS >>>>>>>>>>>>>>>>>>>
// puntos
puntos ::= IZQLLAVE puntosData:w1 DERLLAVE {: RESULT= new Puntos(w1); :}
;
puntosData ::= KD_DATA IZQCORCH puntosDataList:w1 DERCORCH {: RESULT=w1; :}
;
puntosDataList ::= 
    puntosDataValue:w1 {: ArrayList<Puntos.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | puntosDataList2:w1 puntosDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
puntosDataList2 ::=
    puntosDataValue:w1 COMA {: ArrayList<Puntos.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | puntosDataList2:w1 puntosDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
puntosDataValue ::= 
    IZQLLAVE xValue:w1 COMA yValue:w2 DERLLAVE {: RESULT= new Puntos.Data(w1,w2); :}
    | IZQLLAVE yValue:w2 COMA xValue:w1 DERLLAVE {: RESULT= new Puntos.Data(w1,w2); :}
;

// puntosXt
puntosXt ::= 
    IZQLLAVE puntosXtData:w1 COMA chart:w2 DERLLAVE {: RESULT= new PuntosXt(w1,w2); :}
    | IZQLLAVE chart:w2 COMA puntosXtData:w1 DERLLAVE {: RESULT= new PuntosXt(w1,w2); :}
;
puntosXtData ::= KD_DATA IZQCORCH puntosXtDataList:w1 DERCORCH {: RESULT=w1; :}
;
puntosXtDataList ::= 
    puntosXtDataValue:w1 {: ArrayList<PuntosXt.Data> list= new ArrayList<>(); list.add(w1); RESULT=list; :}
    | puntosXtDataList2:w1 puntosXtDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
puntosXtDataList2 ::= 
    puntosXtDataValue:w1 COMA {: ArrayList<PuntosXt.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | puntosXtDataList2:w1 puntosXtDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
puntosXtDataValue ::= 
    IZQLLAVE xValue:w1 COMA yValue:w2 COMA size:w3 COMA color:w4 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE xValue:w1 COMA yValue:w2 COMA color:w4 COMA size:w3 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE xValue:w1 COMA size:w3 COMA yValue:w2 COMA color:w4 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE xValue:w1 COMA size:w3 COMA color:w4 COMA yValue:w2 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE xValue:w1 COMA color:w4 COMA size:w3 COMA yValue:w2 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE xValue:w1 COMA color:w4 COMA yValue:w2 COMA size:w3 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE yValue:w2 COMA xValue:w1 COMA size:w3 COMA color:w4 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE yValue:w2 COMA xValue:w1 COMA color:w4 COMA size:w3 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE yValue:w2 COMA size:w3 COMA xValue:w1 COMA color:w4 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE yValue:w2 COMA size:w3 COMA color:w4 COMA xValue:w1 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE yValue:w2 COMA color:w4 COMA size:w3 COMA xValue:w1 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE yValue:w2 COMA color:w4 COMA xValue:w1 COMA size:w3 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE size:w3 COMA yValue:w2 COMA xValue:w1 COMA color:w4 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE size:w3 COMA yValue:w2 COMA color:w4 COMA xValue:w1 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE size:w3 COMA xValue:w1 COMA yValue:w2 COMA color:w4 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE size:w3 COMA xValue:w1 COMA color:w4 COMA yValue:w2 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE size:w3 COMA color:w4 COMA xValue:w1 COMA yValue:w2 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE size:w3 COMA color:w4 COMA yValue:w2 COMA xValue:w1 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w4 COMA yValue:w2 COMA size:w3 COMA xValue:w1 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w4 COMA yValue:w2 COMA xValue:w1 COMA size:w3 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w4 COMA size:w3 COMA yValue:w2 COMA xValue:w1 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w4 COMA size:w3 COMA xValue:w1 COMA yValue:w2 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w4 COMA xValue:w1 COMA size:w3 COMA yValue:w2 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w4 COMA xValue:w1 COMA yValue:w2 COMA size:w3 DERLLAVE {: RESULT= new PuntosXt.Data(w1,w2,w3,w4); :}
;

// LINEAS >>>>>>>>>>>>>>>>>>>
// lineas
lineas ::= 
    IZQLLAVE lineasData:w1 COMA chart:w2 DERLLAVE {: RESULT= new Lineas(w1,w2); :}
    | IZQLLAVE chart:w2 COMA lineasData:w1 DERLLAVE {: RESULT= new Lineas(w1,w2); :}
;
lineasData ::= KD_DATA IZQCORCH lineasDataList:w1 DERCORCH {: RESULT=w1; :}
;
lineasDataList ::= 
    lineasDataValue:w1 {: ArrayList<Lineas.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | lineasDataList2:w1 lineasDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
lineasDataList2 ::=
    lineasDataValue:w1 COMA {: ArrayList<Lineas.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | lineasDataList2:w1 lineasDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
lineasDataValue ::= 
    IZQLLAVE name:w1 COMA points:w2 DERLLAVE {: RESULT= new Lineas.Data(w1,w2); :}
    | IZQLLAVE points:w2 COMA name:w1 DERLLAVE {: RESULT= new Lineas.Data(w1,w2); :}
;

// lineasXt
lineasXt ::= 
    IZQLLAVE lineasXtData:w1 COMA chart:w2 DERLLAVE {: RESULT= new LineasXt(w1,w2); :}
    | IZQLLAVE chart:w2 COMA lineasXtData:w1 DERLLAVE {: RESULT= new LineasXt(w1,w2); :}
;
lineasXtData ::= KD_DATA IZQCORCH lineasXtDataList:w1 DERCORCH {: RESULT=w1; :}
;
lineasXtDataList ::= 
    lineasXtDataValue:w1 {: ArrayList<LineasXt.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | lineasXtDataList2:w1 lineasXtDataValue:w2 {: w1.add(w2); RESULT=w1; :}
;
lineasXtDataList2 ::=
    lineasXtDataValue:w1 COMA {: ArrayList<LineasXt.Data> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | lineasXtDataList2:w1 lineasXtDataValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
lineasXtDataValue ::= 
    IZQLLAVE name:w1 COMA pointsXt:w2 COMA color:w3 COMA lineStyle:w4 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE name:w1 COMA pointsXt:w2 COMA lineStyle:w4 COMA color:w3 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE name:w1 COMA color:w3 COMA pointsXt:w2 COMA lineStyle:w4 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE name:w1 COMA color:w3 COMA lineStyle:w4 COMA pointsXt:w2 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE name:w1 COMA lineStyle:w4 COMA color:w3 COMA pointsXt:w2 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE name:w1 COMA lineStyle:w4 COMA pointsXt:w2 COMA color:w3 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE pointsXt:w2 COMA name:w1 COMA color:w3 COMA lineStyle:w4 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE pointsXt:w2 COMA name:w1 COMA lineStyle:w4 COMA color:w3 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE pointsXt:w2 COMA color:w3 COMA name:w1 COMA lineStyle:w4 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE pointsXt:w2 COMA color:w3 COMA lineStyle:w4 COMA name:w1 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE pointsXt:w2 COMA lineStyle:w4 COMA color:w3 COMA name:w1 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE pointsXt:w2 COMA lineStyle:w4 COMA name:w1 COMA color:w3 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w3 COMA pointsXt:w2 COMA name:w1 COMA lineStyle:w4 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w3 COMA pointsXt:w2 COMA lineStyle:w4 COMA name:w1 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w3 COMA name:w1 COMA pointsXt:w2 COMA lineStyle:w4 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w3 COMA name:w1 COMA lineStyle:w4 COMA pointsXt:w2 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w3 COMA lineStyle:w4 COMA name:w1 COMA pointsXt:w2 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE color:w3 COMA lineStyle:w4 COMA pointsXt:w2 COMA name:w1 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE lineStyle:w4 COMA pointsXt:w2 COMA color:w3 COMA name:w1 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE lineStyle:w4 COMA pointsXt:w2 COMA name:w1 COMA color:w3 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE lineStyle:w4 COMA color:w3 COMA pointsXt:w2 COMA name:w1 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE lineStyle:w4 COMA color:w3 COMA name:w1 COMA pointsXt:w2 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE lineStyle:w4 COMA name:w1 COMA color:w3 COMA pointsXt:w2 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
    | IZQLLAVE lineStyle:w4 COMA name:w1 COMA pointsXt:w2 COMA color:w3 DERLLAVE {: RESULT= new LineasXt.Data(w1,w2,w3,w4); :}
;

// TARJETA >>>>>>>>>>>>>>>>>>>
tarjeta ::= IZQLLAVE KD_DATA IZQLLAVE tarjetaData:w1 DERLLAVE DERLLAVE {: RESULT=w1; :}
;
tarjetaData ::= 
    value:w1 COMA label:w2 COMA description:w3 {: RESULT= new Tarjeta(w1,w2,w3); :}
    | value:w1 COMA description:w3 COMA label:w2 {: RESULT= new Tarjeta(w1,w2,w3); :}
    | label:w2 COMA value:w1 COMA description:w3 {: RESULT= new Tarjeta(w1,w2,w3); :}
    | label:w2 COMA description:w3 COMA value:w1 {: RESULT= new Tarjeta(w1,w2,w3); :}
    | description:w3 COMA label:w2 COMA value:w1 {: RESULT= new Tarjeta(w1,w2,w3); :}
    | description:w3 COMA value:w1 COMA label:w2 {: RESULT= new Tarjeta(w1,w2,w3); :}
;
tarjetaXt ::= IZQLLAVE KD_DATA IZQLLAVE tarjetaXtData:w1 DERLLAVE DERLLAVE {: RESULT=w1; :}
;
tarjetaXtData ::= 
    value:w1 COMA label:w2 COMA description:w3 COMA icon:w4 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    /*
    | value:w1 COMA label:w2 COMA description:w3 COMA icon:w4 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA description:w3 COMA color:w5 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA description:w3 COMA color:w5 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA description:w3 COMA link:w6 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA description:w3 COMA link:w6 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA icon:w4 COMA description:w3 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA icon:w4 COMA description:w3 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA icon:w4 COMA color:w5 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA icon:w4 COMA color:w5 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA icon:w4 COMA link:w6 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA icon:w4 COMA link:w6 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA color:w5 COMA icon:w4 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA color:w5 COMA icon:w4 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA color:w5 COMA description:w3 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA color:w5 COMA description:w3 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA color:w5 COMA link:w6 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA color:w5 COMA link:w6 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA link:w6 COMA icon:w4 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA link:w6 COMA icon:w4 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA link:w6 COMA color:w5 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA link:w6 COMA color:w5 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA link:w6 COMA description:w3 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA label:w2 COMA link:w6 COMA description:w3 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA label:w2 COMA icon:w4 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA label:w2 COMA icon:w4 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA label:w2 COMA color:w5 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA label:w2 COMA color:w5 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA label:w2 COMA link:w6 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA label:w2 COMA link:w6 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA icon:w4 COMA label:w2 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA icon:w4 COMA label:w2 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA icon:w4 COMA color:w5 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA icon:w4 COMA color:w5 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA icon:w4 COMA link:w6 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA icon:w4 COMA link:w6 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA color:w5 COMA icon:w4 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA color:w5 COMA icon:w4 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA color:w5 COMA label:w2 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA color:w5 COMA label:w2 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA color:w5 COMA link:w6 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA color:w5 COMA link:w6 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA link:w6 COMA icon:w4 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA link:w6 COMA icon:w4 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA link:w6 COMA color:w5 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA link:w6 COMA color:w5 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA link:w6 COMA label:w2 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA description:w3 COMA link:w6 COMA label:w2 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA description:w3 COMA label:w2 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA description:w3 COMA label:w2 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA description:w3 COMA color:w5 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA description:w3 COMA color:w5 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA description:w3 COMA link:w6 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA description:w3 COMA link:w6 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA label:w2 COMA description:w3 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA label:w2 COMA description:w3 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA label:w2 COMA color:w5 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA label:w2 COMA color:w5 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA label:w2 COMA link:w6 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA label:w2 COMA link:w6 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA color:w5 COMA label:w2 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA color:w5 COMA label:w2 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA color:w5 COMA description:w3 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA color:w5 COMA description:w3 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA color:w5 COMA link:w6 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA color:w5 COMA link:w6 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA link:w6 COMA label:w2 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA link:w6 COMA label:w2 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA link:w6 COMA color:w5 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA link:w6 COMA color:w5 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA link:w6 COMA description:w3 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA icon:w4 COMA link:w6 COMA description:w3 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA description:w3 COMA icon:w4 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA description:w3 COMA icon:w4 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA description:w3 COMA label:w2 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA description:w3 COMA label:w2 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA description:w3 COMA link:w6 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA description:w3 COMA link:w6 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA icon:w4 COMA description:w3 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA icon:w4 COMA description:w3 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA icon:w4 COMA label:w2 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA icon:w4 COMA label:w2 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA icon:w4 COMA link:w6 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA icon:w4 COMA link:w6 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA label:w2 COMA icon:w4 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA label:w2 COMA icon:w4 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA label:w2 COMA description:w3 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA label:w2 COMA description:w3 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA label:w2 COMA link:w6 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA label:w2 COMA link:w6 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA link:w6 COMA icon:w4 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA link:w6 COMA icon:w4 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA link:w6 COMA label:w2 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA link:w6 COMA label:w2 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA link:w6 COMA description:w3 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA color:w5 COMA link:w6 COMA description:w3 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA description:w3 COMA icon:w4 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA description:w3 COMA icon:w4 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA description:w3 COMA color:w5 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA description:w3 COMA color:w5 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA description:w3 COMA label:w2 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA description:w3 COMA label:w2 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA icon:w4 COMA description:w3 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA icon:w4 COMA description:w3 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA icon:w4 COMA color:w5 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA icon:w4 COMA color:w5 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA icon:w4 COMA label:w2 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA icon:w4 COMA label:w2 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA color:w5 COMA icon:w4 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA color:w5 COMA icon:w4 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA color:w5 COMA description:w3 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA color:w5 COMA description:w3 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA color:w5 COMA label:w2 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA color:w5 COMA label:w2 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA label:w2 COMA icon:w4 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA label:w2 COMA icon:w4 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA label:w2 COMA color:w5 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA label:w2 COMA color:w5 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA label:w2 COMA description:w3 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | value:w1 COMA link:w6 COMA label:w2 COMA description:w3 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA description:w3 COMA icon:w4 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA description:w3 COMA icon:w4 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA description:w3 COMA color:w5 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA description:w3 COMA color:w5 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA description:w3 COMA link:w6 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA description:w3 COMA link:w6 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA icon:w4 COMA description:w3 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA icon:w4 COMA description:w3 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA icon:w4 COMA color:w5 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA icon:w4 COMA color:w5 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA icon:w4 COMA link:w6 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA icon:w4 COMA link:w6 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA color:w5 COMA icon:w4 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA color:w5 COMA icon:w4 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA color:w5 COMA description:w3 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA color:w5 COMA description:w3 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA color:w5 COMA link:w6 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA color:w5 COMA link:w6 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA link:w6 COMA icon:w4 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA link:w6 COMA icon:w4 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA link:w6 COMA color:w5 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA link:w6 COMA color:w5 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA link:w6 COMA description:w3 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA value:w1 COMA link:w6 COMA description:w3 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA value:w1 COMA icon:w4 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA value:w1 COMA icon:w4 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA value:w1 COMA color:w5 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA value:w1 COMA color:w5 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA value:w1 COMA link:w6 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA value:w1 COMA link:w6 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA icon:w4 COMA value:w1 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA icon:w4 COMA value:w1 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA icon:w4 COMA color:w5 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA icon:w4 COMA color:w5 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA icon:w4 COMA link:w6 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA icon:w4 COMA link:w6 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA color:w5 COMA icon:w4 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA color:w5 COMA icon:w4 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA color:w5 COMA value:w1 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA color:w5 COMA value:w1 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA color:w5 COMA link:w6 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA color:w5 COMA link:w6 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA link:w6 COMA icon:w4 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA link:w6 COMA icon:w4 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA link:w6 COMA color:w5 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA link:w6 COMA color:w5 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA link:w6 COMA value:w1 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA description:w3 COMA link:w6 COMA value:w1 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA description:w3 COMA value:w1 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA description:w3 COMA value:w1 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA description:w3 COMA color:w5 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA description:w3 COMA color:w5 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA description:w3 COMA link:w6 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA description:w3 COMA link:w6 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA value:w1 COMA description:w3 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA value:w1 COMA description:w3 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA value:w1 COMA color:w5 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA value:w1 COMA color:w5 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA value:w1 COMA link:w6 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA value:w1 COMA link:w6 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA color:w5 COMA value:w1 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA color:w5 COMA value:w1 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA color:w5 COMA description:w3 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA color:w5 COMA description:w3 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA color:w5 COMA link:w6 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA color:w5 COMA link:w6 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA link:w6 COMA value:w1 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA link:w6 COMA value:w1 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA link:w6 COMA color:w5 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA link:w6 COMA color:w5 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA link:w6 COMA description:w3 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA icon:w4 COMA link:w6 COMA description:w3 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA description:w3 COMA icon:w4 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA description:w3 COMA icon:w4 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA description:w3 COMA value:w1 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA description:w3 COMA value:w1 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA description:w3 COMA link:w6 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA description:w3 COMA link:w6 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA icon:w4 COMA description:w3 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA icon:w4 COMA description:w3 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA icon:w4 COMA value:w1 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA icon:w4 COMA value:w1 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA icon:w4 COMA link:w6 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA icon:w4 COMA link:w6 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA value:w1 COMA icon:w4 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA value:w1 COMA icon:w4 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA value:w1 COMA description:w3 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA value:w1 COMA description:w3 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA value:w1 COMA link:w6 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA value:w1 COMA link:w6 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA link:w6 COMA icon:w4 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA link:w6 COMA icon:w4 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA link:w6 COMA value:w1 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA link:w6 COMA value:w1 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA link:w6 COMA description:w3 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA color:w5 COMA link:w6 COMA description:w3 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA description:w3 COMA icon:w4 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA description:w3 COMA icon:w4 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA description:w3 COMA color:w5 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA description:w3 COMA color:w5 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA description:w3 COMA value:w1 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA description:w3 COMA value:w1 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA icon:w4 COMA description:w3 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA icon:w4 COMA description:w3 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA icon:w4 COMA color:w5 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA icon:w4 COMA color:w5 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA icon:w4 COMA value:w1 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA icon:w4 COMA value:w1 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA color:w5 COMA icon:w4 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA color:w5 COMA icon:w4 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA color:w5 COMA description:w3 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA color:w5 COMA description:w3 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA color:w5 COMA value:w1 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA color:w5 COMA value:w1 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA value:w1 COMA icon:w4 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA value:w1 COMA icon:w4 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA value:w1 COMA color:w5 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA value:w1 COMA color:w5 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA value:w1 COMA description:w3 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | label:w2 COMA link:w6 COMA value:w1 COMA description:w3 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA value:w1 COMA icon:w4 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA value:w1 COMA icon:w4 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA value:w1 COMA color:w5 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA value:w1 COMA color:w5 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA value:w1 COMA link:w6 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA value:w1 COMA link:w6 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA icon:w4 COMA value:w1 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA icon:w4 COMA value:w1 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA icon:w4 COMA color:w5 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA icon:w4 COMA color:w5 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA icon:w4 COMA link:w6 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA icon:w4 COMA link:w6 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA color:w5 COMA icon:w4 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA color:w5 COMA icon:w4 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA color:w5 COMA value:w1 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA color:w5 COMA value:w1 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA color:w5 COMA link:w6 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA color:w5 COMA link:w6 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA link:w6 COMA icon:w4 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA link:w6 COMA icon:w4 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA link:w6 COMA color:w5 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA link:w6 COMA color:w5 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA link:w6 COMA value:w1 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA label:w2 COMA link:w6 COMA value:w1 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA label:w2 COMA icon:w4 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA label:w2 COMA icon:w4 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA label:w2 COMA color:w5 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA label:w2 COMA color:w5 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA label:w2 COMA link:w6 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA label:w2 COMA link:w6 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA icon:w4 COMA label:w2 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA icon:w4 COMA label:w2 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA icon:w4 COMA color:w5 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA icon:w4 COMA color:w5 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA icon:w4 COMA link:w6 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA icon:w4 COMA link:w6 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA color:w5 COMA icon:w4 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA color:w5 COMA icon:w4 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA color:w5 COMA label:w2 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA color:w5 COMA label:w2 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA color:w5 COMA link:w6 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA color:w5 COMA link:w6 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA link:w6 COMA icon:w4 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA link:w6 COMA icon:w4 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA link:w6 COMA color:w5 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA link:w6 COMA color:w5 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA link:w6 COMA label:w2 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA value:w1 COMA link:w6 COMA label:w2 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA value:w1 COMA label:w2 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA value:w1 COMA label:w2 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA value:w1 COMA color:w5 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA value:w1 COMA color:w5 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA value:w1 COMA link:w6 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA value:w1 COMA link:w6 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA label:w2 COMA value:w1 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA label:w2 COMA value:w1 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA label:w2 COMA color:w5 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA label:w2 COMA color:w5 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA label:w2 COMA link:w6 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA label:w2 COMA link:w6 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA color:w5 COMA label:w2 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA color:w5 COMA label:w2 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA color:w5 COMA value:w1 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA color:w5 COMA value:w1 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA color:w5 COMA link:w6 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA color:w5 COMA link:w6 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA link:w6 COMA label:w2 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA link:w6 COMA label:w2 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA link:w6 COMA color:w5 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA link:w6 COMA color:w5 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA link:w6 COMA value:w1 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA icon:w4 COMA link:w6 COMA value:w1 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA value:w1 COMA icon:w4 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA value:w1 COMA icon:w4 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA value:w1 COMA label:w2 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA value:w1 COMA label:w2 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA value:w1 COMA link:w6 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA value:w1 COMA link:w6 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA icon:w4 COMA value:w1 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA icon:w4 COMA value:w1 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA icon:w4 COMA label:w2 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA icon:w4 COMA label:w2 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA icon:w4 COMA link:w6 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA icon:w4 COMA link:w6 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA label:w2 COMA icon:w4 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA label:w2 COMA icon:w4 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA label:w2 COMA value:w1 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA label:w2 COMA value:w1 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA label:w2 COMA link:w6 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA label:w2 COMA link:w6 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA link:w6 COMA icon:w4 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA link:w6 COMA icon:w4 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA link:w6 COMA label:w2 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA link:w6 COMA label:w2 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA link:w6 COMA value:w1 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA color:w5 COMA link:w6 COMA value:w1 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA value:w1 COMA icon:w4 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA value:w1 COMA icon:w4 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA value:w1 COMA color:w5 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA value:w1 COMA color:w5 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA value:w1 COMA label:w2 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA value:w1 COMA label:w2 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA icon:w4 COMA value:w1 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA icon:w4 COMA value:w1 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA icon:w4 COMA color:w5 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA icon:w4 COMA color:w5 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA icon:w4 COMA label:w2 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA icon:w4 COMA label:w2 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA color:w5 COMA icon:w4 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA color:w5 COMA icon:w4 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA color:w5 COMA value:w1 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA color:w5 COMA value:w1 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA color:w5 COMA label:w2 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA color:w5 COMA label:w2 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA label:w2 COMA icon:w4 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA label:w2 COMA icon:w4 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA label:w2 COMA color:w5 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA label:w2 COMA color:w5 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA label:w2 COMA value:w1 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | description:w3 COMA link:w6 COMA label:w2 COMA value:w1 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA description:w3 COMA value:w1 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA description:w3 COMA value:w1 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA description:w3 COMA color:w5 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA description:w3 COMA color:w5 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA description:w3 COMA link:w6 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA description:w3 COMA link:w6 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA value:w1 COMA description:w3 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA value:w1 COMA description:w3 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA value:w1 COMA color:w5 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA value:w1 COMA color:w5 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA value:w1 COMA link:w6 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA value:w1 COMA link:w6 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA color:w5 COMA value:w1 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA color:w5 COMA value:w1 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA color:w5 COMA description:w3 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA color:w5 COMA description:w3 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA color:w5 COMA link:w6 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA color:w5 COMA link:w6 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA link:w6 COMA value:w1 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA link:w6 COMA value:w1 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA link:w6 COMA color:w5 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA link:w6 COMA color:w5 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA link:w6 COMA description:w3 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA label:w2 COMA link:w6 COMA description:w3 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA label:w2 COMA value:w1 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA label:w2 COMA value:w1 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA label:w2 COMA color:w5 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA label:w2 COMA color:w5 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA label:w2 COMA link:w6 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA label:w2 COMA link:w6 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA value:w1 COMA label:w2 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA value:w1 COMA label:w2 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA value:w1 COMA color:w5 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA value:w1 COMA color:w5 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA value:w1 COMA link:w6 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA value:w1 COMA link:w6 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA color:w5 COMA value:w1 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA color:w5 COMA value:w1 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA color:w5 COMA label:w2 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA color:w5 COMA label:w2 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA color:w5 COMA link:w6 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA color:w5 COMA link:w6 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA link:w6 COMA value:w1 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA link:w6 COMA value:w1 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA link:w6 COMA color:w5 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA link:w6 COMA color:w5 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA link:w6 COMA label:w2 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA description:w3 COMA link:w6 COMA label:w2 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA description:w3 COMA label:w2 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA description:w3 COMA label:w2 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA description:w3 COMA color:w5 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA description:w3 COMA color:w5 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA description:w3 COMA link:w6 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA description:w3 COMA link:w6 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA label:w2 COMA description:w3 COMA color:w5 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA label:w2 COMA description:w3 COMA link:w6 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA label:w2 COMA color:w5 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA label:w2 COMA color:w5 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA label:w2 COMA link:w6 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA label:w2 COMA link:w6 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA color:w5 COMA label:w2 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA color:w5 COMA label:w2 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA color:w5 COMA description:w3 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA color:w5 COMA description:w3 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA color:w5 COMA link:w6 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA color:w5 COMA link:w6 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA link:w6 COMA label:w2 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA link:w6 COMA label:w2 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA link:w6 COMA color:w5 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA link:w6 COMA color:w5 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA link:w6 COMA description:w3 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA value:w1 COMA link:w6 COMA description:w3 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA description:w3 COMA value:w1 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA description:w3 COMA value:w1 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA description:w3 COMA label:w2 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA description:w3 COMA label:w2 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA description:w3 COMA link:w6 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA description:w3 COMA link:w6 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA value:w1 COMA description:w3 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA value:w1 COMA description:w3 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA value:w1 COMA label:w2 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA value:w1 COMA label:w2 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA value:w1 COMA link:w6 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA value:w1 COMA link:w6 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA label:w2 COMA value:w1 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA label:w2 COMA value:w1 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA label:w2 COMA description:w3 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA label:w2 COMA description:w3 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA label:w2 COMA link:w6 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA label:w2 COMA link:w6 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA link:w6 COMA value:w1 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA link:w6 COMA value:w1 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA link:w6 COMA label:w2 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA link:w6 COMA label:w2 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA link:w6 COMA description:w3 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA color:w5 COMA link:w6 COMA description:w3 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA description:w3 COMA value:w1 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA description:w3 COMA value:w1 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA description:w3 COMA color:w5 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA description:w3 COMA color:w5 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA description:w3 COMA label:w2 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA description:w3 COMA label:w2 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA value:w1 COMA description:w3 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA value:w1 COMA description:w3 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA value:w1 COMA color:w5 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA value:w1 COMA color:w5 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA value:w1 COMA label:w2 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA value:w1 COMA label:w2 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA color:w5 COMA value:w1 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA color:w5 COMA value:w1 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA color:w5 COMA description:w3 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA color:w5 COMA description:w3 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA color:w5 COMA label:w2 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA color:w5 COMA label:w2 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA label:w2 COMA value:w1 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA label:w2 COMA value:w1 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA label:w2 COMA color:w5 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA label:w2 COMA color:w5 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA label:w2 COMA description:w3 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | icon:w4 COMA link:w6 COMA label:w2 COMA description:w3 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA description:w3 COMA icon:w4 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA description:w3 COMA icon:w4 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA description:w3 COMA value:w1 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA description:w3 COMA value:w1 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA description:w3 COMA link:w6 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA description:w3 COMA link:w6 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA icon:w4 COMA description:w3 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA icon:w4 COMA description:w3 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA icon:w4 COMA value:w1 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA icon:w4 COMA value:w1 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA icon:w4 COMA link:w6 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA icon:w4 COMA link:w6 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA value:w1 COMA icon:w4 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA value:w1 COMA icon:w4 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA value:w1 COMA description:w3 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA value:w1 COMA description:w3 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA value:w1 COMA link:w6 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA value:w1 COMA link:w6 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA link:w6 COMA icon:w4 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA link:w6 COMA icon:w4 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA link:w6 COMA value:w1 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA link:w6 COMA value:w1 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA link:w6 COMA description:w3 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA label:w2 COMA link:w6 COMA description:w3 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA label:w2 COMA icon:w4 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA label:w2 COMA icon:w4 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA label:w2 COMA value:w1 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA label:w2 COMA value:w1 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA label:w2 COMA link:w6 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA label:w2 COMA link:w6 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA icon:w4 COMA label:w2 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA icon:w4 COMA label:w2 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA icon:w4 COMA value:w1 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA icon:w4 COMA value:w1 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA icon:w4 COMA link:w6 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA icon:w4 COMA link:w6 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA value:w1 COMA icon:w4 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA value:w1 COMA icon:w4 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA value:w1 COMA label:w2 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA value:w1 COMA label:w2 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA value:w1 COMA link:w6 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA value:w1 COMA link:w6 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA link:w6 COMA icon:w4 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA link:w6 COMA icon:w4 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA link:w6 COMA value:w1 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA link:w6 COMA value:w1 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA link:w6 COMA label:w2 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA description:w3 COMA link:w6 COMA label:w2 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA description:w3 COMA label:w2 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA description:w3 COMA label:w2 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA description:w3 COMA value:w1 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA description:w3 COMA value:w1 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA description:w3 COMA link:w6 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA description:w3 COMA link:w6 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA label:w2 COMA description:w3 COMA value:w1 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA label:w2 COMA description:w3 COMA link:w6 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA label:w2 COMA value:w1 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA label:w2 COMA value:w1 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA label:w2 COMA link:w6 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA label:w2 COMA link:w6 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA value:w1 COMA label:w2 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA value:w1 COMA label:w2 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA value:w1 COMA description:w3 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA value:w1 COMA description:w3 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA value:w1 COMA link:w6 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA value:w1 COMA link:w6 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA link:w6 COMA label:w2 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA link:w6 COMA label:w2 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA link:w6 COMA value:w1 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA link:w6 COMA value:w1 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA link:w6 COMA description:w3 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA icon:w4 COMA link:w6 COMA description:w3 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA description:w3 COMA icon:w4 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA description:w3 COMA icon:w4 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA description:w3 COMA label:w2 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA description:w3 COMA label:w2 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA description:w3 COMA link:w6 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA description:w3 COMA link:w6 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA icon:w4 COMA description:w3 COMA label:w2 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA icon:w4 COMA description:w3 COMA link:w6 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA icon:w4 COMA label:w2 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA icon:w4 COMA label:w2 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA icon:w4 COMA link:w6 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA icon:w4 COMA link:w6 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA label:w2 COMA icon:w4 COMA description:w3 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA label:w2 COMA icon:w4 COMA link:w6 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA label:w2 COMA description:w3 COMA icon:w4 COMA link:w6 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA label:w2 COMA description:w3 COMA link:w6 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA label:w2 COMA link:w6 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA label:w2 COMA link:w6 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA link:w6 COMA icon:w4 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA link:w6 COMA icon:w4 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA link:w6 COMA label:w2 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA link:w6 COMA label:w2 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA link:w6 COMA description:w3 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA value:w1 COMA link:w6 COMA description:w3 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA description:w3 COMA icon:w4 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA description:w3 COMA icon:w4 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA description:w3 COMA value:w1 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA description:w3 COMA value:w1 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA description:w3 COMA label:w2 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA description:w3 COMA label:w2 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA icon:w4 COMA description:w3 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA icon:w4 COMA description:w3 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA icon:w4 COMA value:w1 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA icon:w4 COMA value:w1 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA icon:w4 COMA label:w2 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA icon:w4 COMA label:w2 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA value:w1 COMA icon:w4 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA value:w1 COMA icon:w4 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA value:w1 COMA description:w3 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA value:w1 COMA description:w3 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA value:w1 COMA label:w2 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA value:w1 COMA label:w2 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA label:w2 COMA icon:w4 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA label:w2 COMA icon:w4 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA label:w2 COMA value:w1 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA label:w2 COMA value:w1 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA label:w2 COMA description:w3 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | color:w5 COMA link:w6 COMA label:w2 COMA description:w3 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA description:w3 COMA icon:w4 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA description:w3 COMA icon:w4 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA description:w3 COMA color:w5 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA description:w3 COMA color:w5 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA description:w3 COMA value:w1 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA description:w3 COMA value:w1 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA icon:w4 COMA description:w3 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA icon:w4 COMA description:w3 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA icon:w4 COMA color:w5 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA icon:w4 COMA color:w5 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA icon:w4 COMA value:w1 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA icon:w4 COMA value:w1 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA color:w5 COMA icon:w4 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA color:w5 COMA icon:w4 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA color:w5 COMA description:w3 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA color:w5 COMA description:w3 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA color:w5 COMA value:w1 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA color:w5 COMA value:w1 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA value:w1 COMA icon:w4 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA value:w1 COMA icon:w4 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA value:w1 COMA color:w5 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA value:w1 COMA color:w5 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA value:w1 COMA description:w3 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA label:w2 COMA value:w1 COMA description:w3 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA label:w2 COMA icon:w4 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA label:w2 COMA icon:w4 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA label:w2 COMA color:w5 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA label:w2 COMA color:w5 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA label:w2 COMA value:w1 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA label:w2 COMA value:w1 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA icon:w4 COMA label:w2 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA icon:w4 COMA label:w2 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA icon:w4 COMA color:w5 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA icon:w4 COMA color:w5 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA icon:w4 COMA value:w1 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA icon:w4 COMA value:w1 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA color:w5 COMA icon:w4 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA color:w5 COMA icon:w4 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA color:w5 COMA label:w2 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA color:w5 COMA label:w2 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA color:w5 COMA value:w1 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA color:w5 COMA value:w1 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA value:w1 COMA icon:w4 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA value:w1 COMA icon:w4 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA value:w1 COMA color:w5 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA value:w1 COMA color:w5 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA value:w1 COMA label:w2 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA description:w3 COMA value:w1 COMA label:w2 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA description:w3 COMA label:w2 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA description:w3 COMA label:w2 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA description:w3 COMA color:w5 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA description:w3 COMA color:w5 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA description:w3 COMA value:w1 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA description:w3 COMA value:w1 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA label:w2 COMA description:w3 COMA color:w5 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA label:w2 COMA description:w3 COMA value:w1 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA label:w2 COMA color:w5 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA label:w2 COMA color:w5 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA label:w2 COMA value:w1 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA label:w2 COMA value:w1 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA color:w5 COMA label:w2 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA color:w5 COMA label:w2 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA color:w5 COMA description:w3 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA color:w5 COMA description:w3 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA color:w5 COMA value:w1 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA color:w5 COMA value:w1 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA value:w1 COMA label:w2 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA value:w1 COMA label:w2 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA value:w1 COMA color:w5 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA value:w1 COMA color:w5 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA value:w1 COMA description:w3 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA icon:w4 COMA value:w1 COMA description:w3 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA description:w3 COMA icon:w4 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA description:w3 COMA icon:w4 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA description:w3 COMA label:w2 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA description:w3 COMA label:w2 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA description:w3 COMA value:w1 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA description:w3 COMA value:w1 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA icon:w4 COMA description:w3 COMA label:w2 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA icon:w4 COMA description:w3 COMA value:w1 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA icon:w4 COMA label:w2 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA icon:w4 COMA label:w2 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA icon:w4 COMA value:w1 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA icon:w4 COMA value:w1 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA label:w2 COMA icon:w4 COMA description:w3 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA label:w2 COMA icon:w4 COMA value:w1 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA label:w2 COMA description:w3 COMA icon:w4 COMA value:w1 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA label:w2 COMA description:w3 COMA value:w1 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA label:w2 COMA value:w1 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA label:w2 COMA value:w1 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA value:w1 COMA icon:w4 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA value:w1 COMA icon:w4 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA value:w1 COMA label:w2 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA value:w1 COMA label:w2 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA value:w1 COMA description:w3 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA color:w5 COMA value:w1 COMA description:w3 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA description:w3 COMA icon:w4 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA description:w3 COMA icon:w4 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA description:w3 COMA color:w5 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA description:w3 COMA color:w5 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA description:w3 COMA label:w2 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA description:w3 COMA label:w2 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA icon:w4 COMA description:w3 COMA color:w5 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA icon:w4 COMA description:w3 COMA label:w2 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA icon:w4 COMA color:w5 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA icon:w4 COMA color:w5 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA icon:w4 COMA label:w2 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA icon:w4 COMA label:w2 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA color:w5 COMA icon:w4 COMA description:w3 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA color:w5 COMA icon:w4 COMA label:w2 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA color:w5 COMA description:w3 COMA icon:w4 COMA label:w2 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA color:w5 COMA description:w3 COMA label:w2 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA color:w5 COMA label:w2 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA color:w5 COMA label:w2 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA label:w2 COMA icon:w4 COMA color:w5 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA label:w2 COMA icon:w4 COMA description:w3 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA label:w2 COMA color:w5 COMA icon:w4 COMA description:w3 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA label:w2 COMA color:w5 COMA description:w3 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA label:w2 COMA description:w3 COMA color:w5 COMA icon:w4 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
    | link:w6 COMA value:w1 COMA label:w2 COMA description:w3 COMA icon:w4 COMA color:w5 {: RESULT= new TarjetaXt(w1,w2,w3,w4,w5,w6); :}
*/
;

// CASI TERMINALES

// KD_DATA = "data":

// MI_INTEGER = 31
// MI_COLOR = "#33ff57"
// MI_URL = "https://example.com/more-info"
// MI_TEXTO = "Mi Página Web"



// PROPERTY

// KD_TITLE = "title": 
title ::= KD_TITLE MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_DESCRIP = "description": 
description ::= KD_DESCRIP MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_HEADER = "header":
header ::= KD_HEADER IZQLLAVE title:w1 DERLLAVE {: RESULT=w1; :}
;
// KD_FOOTER = "footer":
footer ::= KD_FOOTER IZQLLAVE copyright:w1 DERLLAVE {: RESULT=w1; :}
;
// KD_BACKGR = "backgroundColor":
backgr ::= KD_BACKGR MI_COLOR:w1 {: RESULT=w1; :}
;
// KD_FONTFAM = "fontFamily":
fontFam ::= KD_FONTFAM MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_FONTSIZE = "fontSize":
fontSize ::= KD_FONTSIZE MI_TEXTO:w1 {: RESULT=w1; :}
;


// BARRAS.DATA

// KD_CATEGORY = "category":
category ::= KD_CATEGORY MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_VALUE = "value":
value ::= KD_VALUE MI_INTEGER:w1 {: RESULT=w1; :}
;
// KD_COLOR = "color":
color ::= KD_COLOR MI_COLOR:w1 {: RESULT=w1; :}
;

// KD_LINE = "lineStyle":
lineStyle ::= KD_LINE MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_NAME = "name":
name ::= KD_NAME MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_LABEL = "label":
label ::= KD_LABEL MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_ICON = "icon":
icon ::= KD_ICON MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_LINK = "link":
link ::= KD_LINK MI_URL:w1 {: RESULT=w1; :}
;
// KD_COPYR = "copyright":
copyright ::= KD_COPYR MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_XLABEL = "xAxisLabel":
xLabel ::= KD_XLABEL MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_YLABEL = "yAxisLabel":
yLabel ::= KD_YLABEL MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_LEGEND = "legendPosition":
legend ::= KD_LEGEND MI_TEXTO:w1 {: RESULT=w1; :}
;
// KD_X = "x":
xValue ::= KD_X MI_INTEGER:w1 {: RESULT=w1; :}
;
// KD_Y = "y":
yValue ::= KD_Y MI_INTEGER:w1 {: RESULT=w1; :}
;
// KD_SIZE = "size":
size ::= KD_SIZE MI_INTEGER:w1 {: RESULT=w1; :}
;

// KD_CHART = "chart":
chart ::= KD_CHART IZQLLAVE title:w1 COMA xLabel:w2 COMA yLabel:w3 DERLLAVE {: RESULT= new Chart1(w1,w2,w3); :}
;
pastelXtChart ::= KD_CHART IZQLLAVE title:w1 COMA legend:w2 DERLLAVE {: RESULT= new Chart2(w1,w2); :}
;

// usado en properties
// KD_KEYWORDS = "keywords":
keywords ::= KD_KEYWORDS IZQCORCH keywordList:w1 DERCORCH {: RESULT=w1; :}
;
// keywordList = "página web", "ejemplo", "JSON"
keywordList ::=
    /* epsilon */ {: ArrayList<String> list = new ArrayList<>(); RESULT=list; :}
    | MI_TEXTO:w1 {: ArrayList<String> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | keywordList2:w1 MI_TEXTO:w2 {: w1.add(w2); RESULT=w1; :}
;
keywordList2 ::=
    MI_TEXTO:w1 COMA {: ArrayList<String> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | keywordList2:w1 MI_TEXTO:w2 COMA {: w1.add(w2); RESULT=w1; :}
;

// usado en lineas
// KD_PONTS = "points":
points ::= KD_PONTS IZQCORCH pointList:w1 DERCORCH {: RESULT=w1; :}
;
pointList ::= 
    pointValue:w1 {: ArrayList<Lineas.Data.Punto> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pointList2:w1 pointValue:w2 {: w1.add(w2); RESULT=w1; :}
;
pointList2 ::=
    pointValue:w1 COMA {: ArrayList<Lineas.Data.Punto> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pointList2:w1 pointValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
pointValue ::= IZQLLAVE xValue:w1 COMA yValue:w2 DERLLAVE {: RESULT= new Lineas.Data.Punto(w1,w2); :}
;

// usado en lineasXt
pointsXt ::= KD_PONTS IZQCORCH pointXtList:w1 DERCORCH {: RESULT=w1; :}
;
pointXtList ::= 
    pointXtValue:w1 {: ArrayList<LineasXt.Data.Punto> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pointXtList2:w1 pointXtValue:w2 {: w1.add(w2); RESULT=w1; :}
;
pointXtList2 ::=
    pointXtValue:w1 COMA {: ArrayList<LineasXt.Data.Punto> list = new ArrayList<>(); list.add(w1); RESULT=list; :}
    | pointXtList2:w1 pointXtValue:w2 COMA {: w1.add(w2); RESULT=w1; :}
;
pointXtValue ::= IZQLLAVE xValue:w1 COMA yValue:w2 COMA label:w3 DERLLAVE {: RESULT= new LineasXt.Data.Punto(w1,w2,w3); :}
;
